env: "local"  # Указывает среду выполнения приложения. Возможные значения:
              # - "local" - для локальной разработки,
              # - "dev" - для среды разработки (например, тестирование в команде),
              # - "prod" - для продакшен-среды (выпуск в реальную эксплуатацию).
              # Этот параметр будет использоваться для настройки логгера, уровня логирования и других параметров.

storage_path: "../../storage/storage.db"  # Путь к базе данных SQLite, где будет храниться информация.
                                          # "storage.db" - это файл базы данных, и путь "../../" указывает, что файл находится
                                          # в родительской директории проекта в папке "storage".

http_server:  # Конфигурация для HTTP-сервера.
  address: "localhost:8082"  # Адрес и порт, на котором сервер будет слушать входящие соединения.
                             # Здесь сервер будет работать на localhost (локальный хост) на порту 8082.
  timeout: 4s  # Максимальное время ожидания для ответа сервера. После 4 секунд без ответа соединение будет закрыто.
  idle_timeout: 60s  # Время бездействия соединения. Если соединение не активно в течение 60 секунд, оно будет закрыто.
